export const BlogActionTypes = {
    BLOG_LIST_MULTIPLE: "BLOG_LIST_MULTIPLE",
    BLOG_LIST_USER_MULTIPLE: "BLOG_LIST_USER_MULTIPLE",
    BLOG_SET_REFRESHING: "BLOG_SET_REFRESHING",
    BLOG_EDIT: "BLOG_EDIT"
};